services:
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: cloud_db
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql
    networks:
      - cloud_net
    ports:
      - "5432:5432"

networks:
  cloud_net:
    driver: bridge
